[default]
DEBUG=true

QUERY='"grazing land" OR pastureland OR pasture OR rangeland OR grassland OR savanna OR savannah OR shrubland OR "forage crop" OR "perennial forage" '
FILTER_LANG='en|pt|fr|es'
MAXYEAR='-2023'


VERSION='001'
MONGO_URI='mongodb://localhost:27020'
MINIO_ENDPOINT='localhost:9000'
MINIO_ACCESS_KEY='admin'
MINIO_SECRET_KEY='password'
MINIO_BUCKET_NAME='public'
MINIO_URL='http://localhost:9000/public'
CORES=48